// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: priv.proto

package server

import (
	"context"

	"overall/modules/rpc/auth/internal/logic/priv"
	"overall/modules/rpc/auth/internal/svc"
	"overall/modules/rpc/auth/pb/priv"
)

type PrivServer struct {
	svcCtx *svc.ServiceContext
	priv.UnimplementedPrivServer
}

func NewPrivServer(svcCtx *svc.ServiceContext) *PrivServer {
	return &PrivServer{
		svcCtx: svcCtx,
	}
}

// 检查 token 过期
func (s *PrivServer) CheckTokenExpire(ctx context.Context, in *priv.CheckTokenExpireReq) (*priv.CheckTokenExpireResp, error) {
	l := privlogic.NewCheckTokenExpireLogic(ctx, s.svcCtx)
	return l.CheckTokenExpire(in)
}
