// Code generated by tools. DO NOT EDIT.
package xerr

const (
	OK         uint32 = 0
	ServerBusy uint32 = iota + 100000000
	RequestParamError
	SQLError
	NoRecord
	FieldNotSet
	FieldTypeError
	FilterNeeded
	ActionNoPermission
	ActionNoPermission1
	NameExist
	FileNotExist
	UploadFailed
	UploadFileTooLarge
	UploadFileTypeNotAllowed
)
