// Code generated by tools. DO NOT EDIT.
package xerr

var message map[uint32]string

func init() {
	message = make(map[uint32]string)
	message[OK] = "OK"
	message[ServerBusy] = "ServerBusy"
	message[RequestParamError] = "RequestParamError"
	message[SQLError] = "SQLError"
	message[NoRecord] = "NoRecord"
	message[FieldNotSet] = "FieldNotSet"
	message[FieldTypeError] = "FieldTypeError"
	message[FilterNeeded] = "FilterNeeded"
	message[ActionNoPermission] = "ActionNoPermission"
	message[ActionNoPermission1] = "ActionNoPermission1"
	message[NameExist] = "NameExist"
	message[FileNotExist] = "FileNotExist"
	message[UploadFailed] = "UploadFailed"
	message[UploadFileTooLarge] = "UploadFileTooLarge"
	message[UploadFileTypeNotAllowed] = "UploadFileTypeNotAllowed"
}

func MapErrMsg(errcode uint32) string {
	if msg, ok := message[errcode]; ok {
		return msg
	} else {
		return "server is busy."
	}
}

func IsCodeErr(errcode uint32) bool {
	if _, ok := message[errcode]; ok {
		return true
	} else {
		return false
	}
}
