// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: priv.proto

package priv

import (
	"context"

	"overall/modules/rpc/auth/pb/priv"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CheckTokenExpireReq  = priv.CheckTokenExpireReq
	CheckTokenExpireResp = priv.CheckTokenExpireResp

	Priv interface {
		// 检查 token 过期
		CheckTokenExpire(ctx context.Context, in *CheckTokenExpireReq, opts ...grpc.CallOption) (*CheckTokenExpireResp, error)
	}

	defaultPriv struct {
		cli zrpc.Client
	}
)

func NewPriv(cli zrpc.Client) Priv {
	return &defaultPriv{
		cli: cli,
	}
}

// 检查 token 过期
func (m *defaultPriv) CheckTokenExpire(ctx context.Context, in *CheckTokenExpireReq, opts ...grpc.CallOption) (*CheckTokenExpireResp, error) {
	client := priv.NewPrivClient(m.cli.Conn())
	return client.CheckTokenExpire(ctx, in, opts...)
}
