// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: login.proto

package server

import (
	"context"

	"overall/modules/rpc/auth/internal/logic/login"
	"overall/modules/rpc/auth/internal/svc"
	"overall/modules/rpc/auth/pb/login"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginServer
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

// 登录
func (s *LoginServer) AccountLogin(ctx context.Context, in *login.AccountLoginReq) (*login.LoginResp, error) {
	l := loginlogic.NewAccountLoginLogic(ctx, s.svcCtx)
	return l.AccountLogin(in)
}

// 退出登录
func (s *LoginServer) Logout(ctx context.Context, in *login.LogoutReq) (*login.LogoutResq, error) {
	l := loginlogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}
